name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
    - name: Restore dependencies (.NET)
      run: dotnet restore
    - name: Install test framework for library tests
      run: dotnet add VindicateLibTests/VindicateLibTests.csproj package MSTest.TestFramework
    - name: Restore dependencies (NuGet)
      run: nuget restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
